### ISSUE TITLE
Fehlermeldung mit Python 3.10.12 Ubuntu 22

### ISSUE THREAD

**Issue by riker65** [littleyoda/hibiscus_tradeRepublicExporter#2]
Fehlermeldung mit Python 3.10.12 Ubuntu 22

Habe es auch mal unter Ubuntu versucht. Dort kommt aber ein Fehler.

`
x@ub10:~/hibiscus_tradeRepublicExporter$ python3 -m venv venv
x@ub10:~/hibiscus_tradeRepublicExporter$ . ./venv/bin/activate
(venv) x@ub10:~/hibiscus_tradeRepublicExporter$ python3 tr2hibiscusxml.py  hibiscus --last-days 14 hibiscus/
Traceback (most recent call last):
  File "/home/x/hibiscus_tradeRepublicExporter/tr2hibiscusxml.py", line 11, in <module>
    from hibiscusexport import HIBISCUS
  File "/home/x/hibiscus_tradeRepublicExporter/hibiscusexport.py", line 225
    comment += f"{e["title"]} {e["subtitle"]} {e["amount"]}"
                     ^^^^^
SyntaxError: f-string: unmatched '['
`

bei windows habe ich die Version:3.13.0

**Comment by littleyoda** [comment]
Ich hatte das Skript mit python 3.12 entwickelt und getestet.

Die Version von gerade läuft aber auch mit der 3.10.

**Comment by riker65** [comment]
stimmt , bei mir nach git pull, nun auch.
Danke

aber auch hier der Fehler:


```
ID 43322807-3354-4924-b5a8-6c68c8894e0f
20:24:30 Unknown status EXECUTED CREATED ID: 43322807-3354-4924-b5a8-6c68c8894e0f
20:24:30 Already seen 6a2aa7cb-d80b-4d69-83cc-c83d9035839e
```
Dann liegt es wohl nicht an der Umgebung.

**Comment by riker65** [comment]
can be closed
